batch_size: 102
nb_samp: 59049 #number of sample in trainset batch configuration
base_dir: /DB

#optimizer
optimizer: Adam
opt_decay: 0.0001
amsgrad: 1

lr: 0.001
dev_scp: /DB/VoxCeleb1/feature/waveform/dev_wav_pe.scp
eval_scp: /DB/VoxCeleb1/feature/waveform/eval_wav_pe.scp
epoch: 100
save_dir: /exp/model/networks/
name: reproduce_RawNet
mg: 1 #flag for multi-GPU training
nb_gpu: 2 #number of GPUs
c_lambda: 0.001
trials: /DB/VoxCeleb1/voxceleb1_test.txt
val_trials: /DB/VoxCeleb1/voxceleb1_val.txt
save_best_only: 0

gru_embeddings: /exp/data/

model:
  nb_s_conv_filt: 128
  initializer: he_normal
  wd: 0.0001
  nb_conv_filt: [[128, 128], [256, 256], [256, 256], 256]
  nb_dense_node: [128]
  c_alpha: 0.5
  

