batch_size: 120
base_dir: /DB
optimizer: Adam
opt_decay: 0.0001
amsgrad: 1
lr: 0.001

dev_scp: /DB/VoxCeleb1/feature/waveform/dev_wav_pe.scp
eval_scp: /DB/VoxCeleb1/feature/waveform/eval_wav_pe.scp
epoch: 1000
save_dir: /exp/model/networks/
name: reproduce_bvec
nb_batch_per_epoch: 1000
trials: /DB/VoxCeleb1/voxceleb1_test.txt
val_trials: /DB/VoxCeleb1/voxceleb1_val.txt

gru_embeddings: /exp/data/speaker_embeddings_RawNet
save_best_only: 1

model:
  #nb_dense_node: [512, 512, 512, 512] 
  nb_dense_node: [1024, 1024, 1024, 1024] 
  initializer: RandomUniform
  wd: 0.00005
  dim_embedding: 128
  drop_ratio: 0.5
